#### Numpy
##### Numpy is the fundamental library for scientific computing in python. It provides support for arrays and matrices , along with collection of mathematical functions to operate on these data structures.

In [7]:
import numpy as np

## create array using numpy
## create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row and 5 columns
# if you will use 1,4 it won't work since there are 5 elements not 4 elements

array([[1, 2, 3, 4, 5]])

In [ ]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape # here we used nested list as so we can we shape as (1, 5) instead of (5,)


(1, 5)

In [14]:
# 2d array

arr2=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr2.shape)
print(arr2)

(2, 5)
[[1 2 3 4 5]
 [6 7 8 9 0]]


In [ ]:
# used to display numbers between 0 and 10 with a gap of 2
np.arange(0,10,2)
np.arange(0,10,2).reshape(5,1) # this just reshaped the array into 5 rows and 1 column

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
#np.ones creates an array filled with 1s, used for initializing arrays, matrix operations, masks, or placeholders in NumPy
arr3=np.ones((3,4))
print(arr3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)            # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)        # Output: int64 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [24]:
# Numpy vectorized operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## element wise addition
print("addition:",arr1+arr2)

## element wise subtraction
print("subtraction:",arr1-arr2)

## element wise multiplication
print("multiplication:",arr1*arr2)

## element wise division
print("division:",arr1/arr2)



addition: [11 22 33 44 55]
subtraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]


In [25]:
## Universal function
arr=np.array([1,2,3,4,5,6])

## square root
print(np.sqrt(arr))

## exponential
print(np.exp(arr))

## sine
print(np.sin(arr))

## natural log
print(np.log(arr))


[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [26]:
## array slicing and indexing

arr=np.array([[1,2,3,5],[9,10,11,12],[3,6,8,9]])
print("array:\n",arr)

array:
 [[ 1  2  3  5]
 [ 9 10 11 12]
 [ 3  6  8  9]]


In [ ]:
arr[0][0]
print(arr[0:2,2:]) ## what it basically does is that it reads from column 0 and till the end 1 row(n-1 kind of thing) , start from 0 row to 2 (but it takes to 1 as n-1 thing then what it does is , it starts from 2 column and goes up to the end in 1st row and 2nd row)


[[ 3  5]
 [11 12]]


In [28]:
arr[1:,2:] ## row 1 to end of all rows and column 2 to end of all columns

array([[11, 12],
       [ 8,  9]])

In [31]:
## modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   5]
 [  9  10  11  12]
 [  3   6   8   9]]


In [32]:
# replace all the elements by 100 till the end of the array
arr[1:]=100
print(arr)

[[100   2   3   5]
 [100 100 100 100]
 [100 100 100 100]]


In [33]:
## statistical concepts : Normalization
## to have a mean of zero and standard deviation of 1

data=np.array([1,2,3,4,5])

# calculate the mean and standard deviation
mean=np.mean(data)
std_dev=np.std(data)

#normalize the data
normalized_data=(data-mean)/std_dev
print("normalized data:",normalized_data)

normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [34]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [36]:
## logical operations

data=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

data[(data>5) & (data<=8)]

array([6, 7, 8])